### ISSUE TITLE
Pull global trial end date from trial results page as well

### ISSUE THREAD

**Issue by bgcarlisle** [bgcarlisle/euctrscrape#1]
Add closure date from trial results page to the returned variables for `euctr_results_posted`

E.g. See https://www.clinicaltrialsregister.eu/ctr-search/trial/2010-023457-11/results

The "Global completion date" is "08 Feb 2012" (reformat as date)

**Comment by bgcarlisle** [comment]
Hey @maia-sh

It looks like sometimes "Global completion date" isn't listed, but "Global end of trial date" is, e.g. https://www.clinicaltrialsregister.eu/ctr-search/trial/2012-001661-32/results

You wouldn't happen to know off the top of your head if there's documentation or anything that lists what variations on this phrase are possible, would you?

**Comment by maia-sh** [comment]
lol. I know some elements come from National Competent Authorities, but I'm really not sure. I'm speaking with Nick tomorrow morning and can ask or you can email him. He's a solid bet for know if there is knowledge to be known on this.

**Comment by bgcarlisle** [comment]
Okay I just implemented it so that it looks for "Global completion date" then "Global end of trial date" and if neither is there, returns NA

https://github.com/bgcarlisle/euctrscrape/commit/e06c7a3d276b72598c71c823b02c58eefae91ae1
