### ISSUE TITLE
Functions may not be exported

### ISSUE THREAD

**Issue by maia-sh** [bgcarlisle/euctrscrape#2]
Hi @bgcarlisle 👋 

I'm only able to run `euctr_reg_dates()` and it seems the others may not be exported:
![Screen Shot 2022-05-05 at 18 43 29](https://user-images.githubusercontent.com/38968656/166972044-e5799b59-638f-4c8e-977b-4f46e55919be.png)

**Comment by bgcarlisle** [comment]
Ah, forgot to call `document()` before pushing! https://github.com/bgcarlisle/euctrscrape/commit/fadd568f0ab5b8bd2721181a3bb118a11da395b8 Fixed!
